server:
  port: 9966
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: haohuigou-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bawudihe/haohuigou_config.git  #git文件地址
          username: bawudihe
          password: humingdiyi1